### ISSUE TITLE
Implement a Landing page

### ISSUE THREAD

**Issue by willychangx** [cram-connect/cram-connect#1]
Do all work for this task in a branch called issue-01

Illustrate how to implement a Landing page:
- [x] Create a Landing page
- [x] Create a button where the user can sign-in

**Comment by saharama** [comment]
![m1-landing](https://user-images.githubusercontent.com/25652024/79620253-0501fa00-80ab-11ea-8ba9-1e0653f0bb76.jpg)

Good job Marionne!
