### ISSUE TITLE
Implement a Profile page

### ISSUE THREAD

**Issue by willychangx** [cram-connect/cram-connect#8]
Do all work for this task in a branch called issue-08

Illustrate how to implement a Profile page:

- [x] Create a page called Profile
- [x] Create editable fields for the user's information
- [x] Save user's information if "Save Profile" is pressed

**Comment by saharama** [comment]
Editable fields for First Name, Last Name, Major, and Image URL are implemented. EditProfile page also displays the current profile image, and it can be changed through a Sweet Alert notification/input.

Currently, this pulls from a Profiles collection, which uses the email field to identify the respective user in the User collection. Not sure if this should be consolidated into one collection or not.

Inputs for Preferences and Favorite Spot can be added as collections from the other pages are created.

**Comment by saharama** [comment]
@willychangx Please deploy this to Galaxy

**Comment by saharama** [comment]
![m1-editProfile](https://user-images.githubusercontent.com/25652024/79620332-44c8e180-80ab-11ea-8ca6-91584512eb72.JPG)
![m1-editProfile-swal](https://user-images.githubusercontent.com/25652024/79620334-4692a500-80ab-11ea-9fda-b4365b50f8ab.jpg)

Good job me!
